# Generated by Django 5.0.4 on 2024-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_myuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Обычный пользователь"), (2, "Менеджер")], default=1
            ),
        ),
    ]
